# Generated by Django 6.0.4 on 2026-05-02 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecine_generale',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_consultation.consultation')),
                ('poids', models.FloatField()),
                ('taille', models.FloatField()),
                ('temperature', models.FloatField()),
                ('IMC', models.FloatField()),
                ('diagnostic', models.CharField(default='', max_length=500)),
                ('traitement_en_cours', models.CharField(default='', max_length=500)),
            ],
            bases=('gestion_consultation.consultation',),
        ),
        migrations.CreateModel(
            name='Ophtalmologie',
            fields=[
                ('consultation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gestion_consultation.consultation')),
                ('vision_OG', models.CharField(default='', max_length=500)),
                ('vision_OD', models.CharField(default='', max_length=500)),
                ('tension', models.CharField(default='', max_length=500)),
                ('refraction', models.CharField(default='', max_length=500)),
            ],
            bases=('gestion_consultation.consultation',),
        ),
        migrations.AddField(
            model_name='consultation',
            name='antecedents',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='consultation',
            name='motif_consultation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
